### PR TITLE
 Add C++ layers for DetectNet and include Caffe version

### PR DESCRIPTION
**Pull request by lunzueta**
This pull request includes two new layers, "L1Loss" and "DetectnetTransformation", which are already included in NVIDIA's Caffe fork (https://github.com/NVIDIA/caffe). These layers are used in NVIDIA's DIGITS (https://github.com/NVIDIA/DIGITS) for object detection (https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection) and image segmentation (https://github.com/NVIDIA/DIGITS/tree/master/examples/segmentation).

Besides, as DIGITS needs to verify the Caffe version from the CAFFE_VERSION variable (otherwise it doesn't work), and the current Windows version of Caffe doesn't define it (it is included in CMakeLists.txt of the root folder, but not in any Visual Studio project), this pull request also includes it in the "preprocessor definitions" of the following Visual Studio projects, which use this variable too: caffe, pycaffe and matcaffe.

### CODE REVIEW

**Comment by lunzueta** [comment]
I have already tested the changes using my compiled Caffe version with NVIDIA's DIGITS running in Windows 10 and I can train the new models normally.

**Comment by zer0n** [comment]
Thanks @lunzueta 

We have been adding object detection capabilities, e.g. Faster R-CNN and R-FCN (see [this PR](https://github.com/Microsoft/caffe/pull/107)). So what are the advantages of DetectNet? If it's specific to NVidia's use cases, we may not want to add it.

I'm OK with the other changes.

**Comment by lunzueta** [comment]
Hi @zer0n. I'm aware of Faster R-CNN and R-FCN detection methods. The layers included in this pull request would allow deploying approaches like DetectNet for object detection and others for image segmentation. In this link (https://devblogs.nvidia.com/parallelforall/detectnet-deep-neural-network-object-detection-digits/), you can find more info about DetectNet, and its advantages compared to other state-of-the-art detection methods.

For me (and probably for other users too), it's quite comfortable to try different kinds of nets by using DIGITS for training/testing (as it's very visual), and then once I get an appropriate net, use Caffe for deployment (DIGITS can't be used for deployment, just for training/testing). So, it would be nice to be able to get the DetectNet approach too for deployment in Windows, as it already can be done in Linux (using NVIDIA's Caffe fork which isn't compatible with Windows). Thanks.

**Comment by zer0n** [comment]
Thanks. Let's wait for the R-FCN PR to be merged first? It's almost done, but I'm on vacation and can't get to finishing it.

**Comment by lunzueta** [comment]
Sure. No rush. Enjoy you holidays :-)

**Comment by lunzueta** [comment]
Sorry. Maybe I precipitated with this PR. I've seen it still needs further improvements from my side, which I hope I can solve during the following days.

The changes included up to now are mainly based on this commit from NVIDIA's Caffe fork (https://github.com/NVIDIA/caffe/commit/ba120c1a502809a949990c600e101edbda8ec71e). This is enough for deploying the mentioned segmentation approach (which I already had tested before submitting the PR), but I still didn't complete the testing of DetectNet. Now I've realized that there are more related commits in NVIDIA's Caffe fork for DetectNet, which I'm integrating currently. I'll upload them once I've tested all this in Windows and also in Linux (now easier to test in my machine thanks to the new Linux bash integrated in Windows :-P).

**Comment by IsaacYangSLA** [comment]
I have a working detectnet in [Caffe for Windows](https://github.com/isaacyangsla/caffe/tree/windows). After building it with Visual Studio 2013 (release build), point your DIGITS to $CAFFE_ROOT/build/x64/release and PYTHONPATH to $CAFFE_ROOT/build/x64/release/pycaffe. It should work in Windows 7 (also tested with GTX 1080).

**Comment by lunzueta** [comment]
Thanks for the info @IsaacYangSLA. I'll check your repo now.

Meanwhile, I just uploaded the files I had missing to make DetectNet work in my fork. I tested it in Windows 10 and everything was fine this time, so I'd say that the PR is ready for revision. I only had available a GTX 745 card, so I had to reduce the dataset size of the KITTI dataset shown in NVIDIA's DIGITS example to start seeing the results in a reasonable time.

**Comment by IsaacYangSLA** [comment]
@lunzueta , great to know you also made detectnet work in Windows.

**Pull request closed without merging**
