### PR TITLE
R-FCN minimum change sets

### PR DESCRIPTION
**Pull request by daijifeng001**
- add position-sensitive RoI pooling
- modify BN and scale layers to save memory

### CODE REVIEW

**Comment by zer0n** [comment]
Thanks @daijifeng001 

The quality test for this PR would be: if we switch caffe from [here](https://github.com/daijifeng001/R-FCN/tree/master/external) to this branch, the [training instructions of R-FCN](https://github.com/daijifeng001/R-FCN) should work seamlessly.

So I think you need to add additional changes to this PR:
- Update the VS solution file
- Add and modify a few MATLAB files?

Also, your code contains mixed tabs and spaces. You need to convert all tabs to spaces to pass the lint test.

**Comment by daijifeng001** [comment]
Hi Kenneth, thanks for your quick response. But the problem is there are many minor modifications to make it compatible with the Matlab interface of R-FCN, which may well be incompatible with/pollute the major branch of Caffe. I intended to keep this pull request simple and clean. Do you have some suggestions?

**Comment by zer0n** [comment]
If we don't add the minor modifications to Caffe, can we update the MATLAB code so that it works with this version of Caffe?

Otherwise, I don't see how uses can consume this branch of Caffe for training R-FCN model.

**Comment by daijifeng001** [comment]
OK. I will give it a try.

**Comment by zer0n** [comment]
In your Caffe version and in the paper, you also have OHEM. I think you should add that to this PR as well.

**Pull request closed without merging**
