### PR TITLE
examples for Windows, new cifar100 example, and loss accuracy plotter

### PR DESCRIPTION
**Pull request by Coderx7**
This is an update from my former pr, which adds the scripts necessary to download, create and run examples on windows. 
I added cifar100 scripts as well, and a new plotter for plotting loss/accuracy curves using caffes training logs. 
Unlike the former pr, which the linux scripts were deleted accidentally, in this pr they are included. 
I also used some 3dparty apps (gnu win32) for mimicking Linux commands and apps on windows.

### CODE REVIEW

**Comment by zer0n** [comment]
Thanks @Coderx7 .

A lot of your changes are out of the scope of this repo. For example: you should only add a few scripts that have equivalent shell scripts. No more.

Plus, for those Windows scripts, may I ask you to use PowerShell? `.bat` is so last century :).

**Comment by Coderx7** [comment]
Thanks for your reply. 
I'm new to github and kind of confused how things are managed here!
so a separate commit that only contains the new scripts, is that what you mean? only new scripts and source codes regardless of their structure?)

**Comment by zer0n** [comment]
Actually, I think that we don't even need to add new scripts just for Windows. Users can just run the available shell scripts using [win-bash](https://sourceforge.net/projects/win-bash/files/shell-complete/latest/), or Cygwin, or MSYS2, for examples.

**Comment by Coderx7** [comment]
If thats a possibility then, why not adding a note to the readme in the first page as a headsup for windows users? 
I myself had alot of problems when I first started caffe on windows. and I know lots and lots of users are only using Linux solely because running examples and different scripts on windows are impossible for them.

**Comment by zer0n** [comment]
Yep. I'll add that to README in the next update.

**Comment by Coderx7** [comment]
@zer0n : That would be great. 
by the way, I however added the changes here : https://github.com/Coderx7/caffe-windows-examples 
this might be useful to someone out there, so I'm posting it here ( not for being merged or what so ever, since being able to run bash scripts on windows voids the sole reason of existence of this pr. )

Thanks

**Pull request closed without merging**
